### ISSUE TITLE
似乎爱奇艺会出问题，会无法播放。

### ISSUE THREAD

**Issue by Gizardry** [koolproxy/koolproxy_rules#10]
弹出“浏览器兼容问题”提示，关闭koolproxy 2.0.9后恢复正常（广告恢复）。之前几天一直是好的，今天用的Mac下的Safari和Chrome，Win下的IE都出现这个问题，应该是爱奇艺有某种识别方法吧。
随便打开一个，如
http://www.iqiyi.com/v_19rrn180bk.html
![default](https://cloud.githubusercontent.com/assets/22597325/20188354/402a7bf4-a7b3-11e6-9466-92198ddcd34e.png)

**Comment by Gizardry** [comment]
之前一直是ok的。

**Comment by houzi-** [comment]
今晚解决
