### ISSUE TITLE
百度贴吧广告

### ISSUE THREAD

**Issue by enuma0** [koolproxy/koolproxy_rules#11]
http://tieba.baidu.com/f?fr=ala0&kw=%B9%D4%C0%EB%D0%D4%B0%D9%CD%F2%D1%C7%C9%AA%CD%F5&tpl=5
百度这种类型的贴吧顶部和底部的广告没有去除掉。

**Comment by houzi-** [comment]
由于没有加入掩藏元素的支持，暂时不能完整过滤！
这个issues暂时关闭
