### ISSUE TITLE
关于规则对YoukuAntiADs(haoutil)项目swf文件引用的说明

### ISSUE THREAD

**Issue by kafan15536900** [koolproxy/koolproxy_rules#17]
koolproxy规则维护择者你好.
非常高兴能看到KoolProxy的不断进步.
在github中KoolProxy播放器替换规则包含yiclear部分.
yiclear与部分开发者在未经过说明的情况下使用了kafan论坛众多开发者参与修改制作的YoukuAntiADs(haoutil)项目swf文件.

ADM,adbyby均在关于等位置进行对kafan论坛或相关人员进行了标注.
能否请KoolProxy在使用相关文件时进行一定的说明,谢谢.

**Comment by houzi-** [comment]
好的，我们一定补充上去，抱歉啊

**Comment by kafan15536900** [comment]
非常感谢,希望在未来能走得更远

2017-02-12 18:00 GMT+08:00 hackshell <notifications@github.com>:
