### ISSUE TITLE
广告过滤规则导致Ios上的查找iphone的地图无法加载出来

### ISSUE THREAD

**Issue by RoeltaNcRave** [koolproxy/koolproxy_rules#23]
此问题存在了很久了，今天才终于找到反馈入口。
规则已经更新到最新，没有任何其他自定义规则。
koolproxy静态规则：【update[rules]: 2017-3-29 14:23】 
koolproxy视频规则：【update[video]: 2017-3-27 12:08 】
出现的问题是，我在ipad上安装了查找iphone这个app，高德地图无法加载显示出来。
关闭广告过滤后可以显示出来（经过多次尝试验证）。
ipad上的原生地图应用的高德地图可以正常显示出来。

**Comment by houzi-** [comment]
不明白如何弄，查找Iphone的我这里打开显示地图没问题

**Comment by houzi-** [comment]
如没有继续反馈，我将要暂时关闭这个issues了
