### ISSUE TITLE
视频规则误杀爱奇艺客户端的泡泡圈

### ISSUE THREAD

**Issue by xJetRy** [koolproxy/koolproxy_rules#24]
路由器系统         梅林7.4
koolshare版本   3.3.2~3.3.6一直存在
app版本             爱奇艺 安卓 8.2、iOS 8.2
影响范围            客户端内泡泡圈
加载视频规则就不能访问，只加载静态规则就正常 已经很久了

**Comment by houzi-** [comment]
已解决
