### ISSUE TITLE
百度知道广告

### ISSUE THREAD

**Issue by wangfuohao** [koolproxy/koolproxy_rules#25]
https://zhidao.baidu.com/question/507168352.html?fr=iks&word=%C4%E3%BA%C3&ie=gbk&qq-pf-to=pcqq.temporaryc2c

希望过滤上方那个了解书法的一切，右边的相关搜索和下方的精彩知识在知道

**Comment by houzi-** [comment]
已经解决，更新规则即可（安装https证书过滤）
