### ISSUE TITLE
发现一个现象但实在分辨不出是不是规则的问题

### ISSUE THREAD

**Issue by wellkens** [koolproxy/koolproxy_rules#3]
我有两个苹果设备，一个手机的IOS8，一个是IPAD的IOS6，打开koolproxy用全局过滤，发现IPAD无法访问APP STORE，手机正常，关闭koolproxy的时候iPad就能访问APP STORE……

**Comment by houzi-** [comment]
等我们排查一下

**Comment by wellkens** [comment]
不好意思，这几天折腾路由器和固件，挨个排查，最终能确定不是koolproxy规则的问题……是固件内APP加速插件的锅……
