### ISSUE TITLE
火狐里爱奇艺无法播放

### ISSUE THREAD

**Issue by 70599** [koolproxy/koolproxy_rules#32]
- 视频地址：
    http://www.iqiyi.com/fun/20130702/43108f8a0ed519aa.html

- 现象：
    没有广告，视频窗口内无限进度条不能播放

- 系统：
    OS X 10.11.6
    Windows 8.1

- KP版本：
    3.5.3（OpenWRT 15.05.1 AR71xx）

- 补充：
    其他浏览器正常（已测试Safari）

**Comment by houzi-** [comment]
正在想办法解决

**Comment by 70599** [comment]
好，我先暂时用adbyby

**Comment by 70599** [comment]
搜了一下，看来是老问题了。。。
http://koolshare.cn/thread-80602-1-1.html

**Comment by 70599** [comment]
确认火狐爱奇艺已修复。
感谢对应。

**Comment by 70599** [comment]
这个问题在我这里看起来又复发了。
@houzi- 有空的时候希望你可以再用火狐测试一下
