### ISSUE TITLE
iOS 优酷客户端一些视频无法播放

### ISSUE THREAD

**Issue by HackerOO7** [koolproxy/koolproxy_rules#34]
koolproxy静态规则： 更新日期：2017-6-1 16:13 / 9450条    
koolproxy视频规则： 更新日期：2017-6-3 23:02
koolproxy 3.5.9.1

更新到3.5.9.1版本后，发现一些视频无法播放，进度圈圈一直旋转

**Comment by houzi-** [comment]
下次更新解决！
