### ISSUE TITLE
是否无法屏蔽网页广告？

### ISSUE THREAD

**Issue by seuplus** [koolproxy/koolproxy_rules#45]
装了 koolproxy 之后，视频广告能屏蔽。但在 Chrome 上把 Adblock 等广告插件关了，并清除缓存，打开 v2ex.com 还是有广告。

是不是 koolproxy 无法屏蔽网页广告？谢谢～

**Comment by sadoneli** [comment]
koolproxy基于规则的，规则里有的就能屏蔽，没有的不能

**Comment by seuplus** [comment]
@sadoneli 谢谢回复。是不是因为 `https://www.v2ex.com` 是 `https` 的原因，导致广告屏蔽没起作用？

**Comment by seuplus** [comment]
@sadoneli 按照论坛教程，在 Mac 上安装了证书，并关闭 Chrome 上的 Adblock 插件，访问 `https://www.v2ex.com` 还是有广告，不知是哪里姿势不对？

**Comment by sadoneli** [comment]
我想表达的意思是，我们没有做v2ex的广告过滤规则
因为考虑到大量的低端路由用户，https过滤会影响这部分用户https网页加载体验，所以https过滤都用着十足必要的地方，比如过滤视频广告什么的，其余的https没有写过滤规则

**Comment by seuplus** [comment]
@sadoneli 好的，明白。再次感谢回复！

**Comment by houzi-** [comment]
@seuplus 
v2ex的规则是有的，并且v2ex的过滤完全没有问题
