### ISSUE TITLE
网易图片类新闻错误过滤

### ISSUE THREAD

**Issue by ikelvingo** [koolproxy/koolproxy_rules#5]
示例网址：
http://money.163.com/photoview/0BGT0025/28152.html

日志：
Oct 18 02:47:52 sissylog: req should block=1 line=1487 url=http://img1.126.net/channel4/024734/tujihzh01_0927.html
Oct 18 02:47:52 sissylog: req should block=1 line=1487 url=http://img1.126.net/channel18/016871/jd50030_0623.jpg
Oct 18 02:47:53 sissylog: should replace block=1 line=0 http://news.163.com/special/00014P41/gallery_rank_data-0025.js
Oct 18 02:47:54 sissylog: req should block=1 line=1487 url=http://img1.126.net/channel18/019398/01t_0403.html
Oct 18 02:47:54 sissylog: req should block=1 line=1487 url=http://img1.126.net/channel4/022134/taobao_tujim3.html
Oct 18 02:47:54 sissylog: resp should block=1 line=3299 url=http://www.googletagservices.com/tag/js/gpt.js
Oct 18 02:47:54 sissylog: req should block=1 line=1334 url=http://g.163.com/r?site=netease&affiliate=163&cat=tuji&type=column960x130&location=1
Oct 18 02:47:54 sissylog: req should block=1 line=2564 url=http://x.jd.com/exsites?spread_type=2&ad_ids=334:5&location_info=0&callback=getjjsku_callback

分析：
img1.126.net的url封锁后会导致所有图片类新闻失效，并且页面框架也混乱了。

**Comment by jannson** [comment]
有这样的 issue 好定位多了。赞一个。会尽快找人优化规则。
