### ISSUE TITLE
user规则白名单问题

### ISSUE THREAD

**Issue by srwgin** [koolproxy/koolproxy_rules#51]
开启koolproxy后 发现某手游不能热更新
然后发现 更新地址是
http://dnw5grz2619mn.cloudfront.net:443/
如果才能在user规则那添加白名单让他能更新
我测试下来
@@http://dnw5grz2619mn.cloudfront.net
或者
@@||.cloudfront.net
都不行
真奇怪

**Comment by houzi-** [comment]
@@|https://dnw5grz2619mn.cloudfront.net

**Comment by srwgin** [comment]
我是用自己PC做代理 然后抓取地址的
抓到的地址是这样的
220ac3f28f8d4cf99d8ce38fc8d4d5a7.baas.nintendo.com:443
dnw5grz2619mn.cloudfront.net:443
但是用你上面格式 还是不行
只有取消443端口 才能正常热更新
真奇怪

**Comment by houzi-** [comment]
@srwgin 你填入的规则是否是https开头的？

**Comment by srwgin** [comment]
是https 因为抓出来的地址是https
难道有问题？

**Comment by houzi-** [comment]
你确定是误杀这个URL吗？你可以直接在KoolProxy交流群里联系我看看

**Comment by srwgin** [comment]
不在群里 我也怀疑可能提取地址有问题
我是用代理软件电脑做代理 截取通信的
2个IOS 日服手游 1个火焰纹章 1个lovelive

**Comment by houzi-** [comment]
@srwgin 还是建议你加一下我们的交流群，来直接找我看看！
