### ISSUE TITLE
有一条内置规则貌似和网易云音乐的评论页冲突

### ISSUE THREAD

**Issue by tsanie** [koolproxy/koolproxy_rules#55]
开启过滤后iOS端网易云音乐app会出现打开评论页一直loading的情况，分析了一下一共会请求三个api：

> music.163.com/eapi/auth/artist
> music.163.com/eapi/ad/get
> music.163.com/eapi/v1/resource/comments/XXXX

其中第二条被`||music.163.com/eapi/ad`规则过滤掉了，或许是该app没有处理这个exception导致评论打不开。

但是既然加入这条过滤规则，应该是某些广告确实使用了这些api，感觉单单删除这个规则也不好，该如何处理呢，`@@||music.163.com/eapi/ad/get`加个白名单？

**Comment by Mattosx** [comment]
同样存在这个问题

**Comment by houzi-** [comment]
已经修复！
