### ISSUE TITLE
打开koolproxy后，小米VIP会员就无法观看VIP视频了。

### ISSUE THREAD

**Issue by siwsal** [koolproxy/koolproxy_rules#56]
当运行打开koolproxy后，小米电视的VIP会员视频就无法观看（小米vip自动认证识别与服务器通信中断），也不能购买VIP（购买页面显示不了）

**Comment by combosnoopy** [comment]
我也是一样的情况，看来需要修改一下规则

**Comment by RiverSharp** [comment]
我家也是这个情况，不知道怎么来处理……

**Comment by liyue2008** [comment]
同样的问题，希望尽快修复
