### ISSUE TITLE
新浪微博图片都打不开了

### ISSUE THREAD

**Issue by guqikay** [koolproxy/koolproxy_rules#6]
新浪微博图片都打不开了

**Comment by AbraxasVi** [comment]
新浪微博图片全灭.........

**Comment by AbraxasVi** [comment]
@@||sinaimg.cn/large/$image
||sinaimg.cn^
有必要把这两条也加进去吗？请大佬们发布前先复核一下好不好，好多条都是重复规则，浪费空间和内存

**Comment by sadoneli** [comment]
https://github.com/koolproxy/koolproxy_rules/commit/975e32f197817c8ab2b2d214aefbdb457c8df4be
