### ISSUE TITLE
koolproxy规则正则匹配是否只支持http链接

### ISSUE THREAD

**Issue by kysdm** [koolproxy/koolproxy_rules#70]
匹配https链接的规则发现没生效
/^https:\/\/www\.\d{4}t\.com\/js\/mobile\.js/
/^https:\/\/www\.\d{4}t\.com\/js\/Collection\.js/
/^https:\/\/www\.\d{4}t\.com\/js\/jquery\.js/$s@btnClose = '<*adRightFloatBottom,ofloat:1})@{@

**Comment by houzi-** [comment]
是的
