### ISSUE TITLE
小米电视购买会员和购买付费内容被屏蔽

### ISSUE THREAD

**Issue by sacredneo** [koolproxy/koolproxy_rules#72]
RT，小米电视中，购买会员和付费内容时不能正常显示

**Comment by combosnoopy** [comment]
小米电视，打开全局规则，会员信息就不显示了，无法使用付费内容，是不是要把其中小米会员的url屏蔽给单独放出来

**Comment by houzi-** [comment]
@combosnoopy 目前我们没有小米盒子，这个问题我们会进行修复！

**Comment by sacredneo** [comment]
规则更新后，小米盒子的开机广告、屏保广告和视频广告都无法过滤

**Comment by yezigl** [comment]
购买会员页面依然无法显示
koolproxy静态规则： 更新日期：2018-1-10 12:22 / 10568条      koolproxy视频规则： 更新日期：2018-1-13 14:11
3.7.0

**Comment by houzi-** [comment]
@sacredneo 现在小米的生态链联系太紧密了，不太好过滤，加上我们规则组没有小米相关的设备抓包分析，有些误杀的都会放开，所以我们整理放出一些规则让用户自行选择添加过滤！

**Comment by houzi-** [comment]
@yezigl 我可能需要你配合远程才能解决这个问题了，加入交流群，在群里私聊我！
