### ISSUE TITLE
百度网盘客户端导致路由器99%占用

### ISSUE THREAD

**Issue by foxdodo** [koolproxy/koolproxy_rules#74]
用百度网盘破解版下载视频时路由器出现cpu 99%占用。关闭koolproxy插件则恢复正常。使用迅雷满带宽下载也不会出现这么高占用

**Comment by houzi-** [comment]
请加交流群联系我：369773525

**Comment by houzi-** [comment]
@foxdodo 我昨天忘记你哪位了，你再发个信息给我一下！

**Comment by eric1932** [comment]
同问
