### ISSUE TITLE
malfunction with Youku iOS app

### ISSUE THREAD

**Issue by shenjatsen** [koolproxy/koolproxy_rules#78]
An issue found on my iphone:
with koolproxy enabled on my ASUS router running merlin firmware, video not able to play on Youku iOS app.
router: RT-AC1900P running 380.68_4-X7.7
koolproxy: 3.7.1
iOS: 11.2.2
youku app: v6.12.0

Thanks in advance.

**Comment by houzi-** [comment]
http://koolshare.cn/forum.php?mod=viewthread&tid=131813&page=1&extra=#pid1370825
