### ISSUE TITLE
新浪微博查看原图被屏蔽

### ISSUE THREAD

**Issue by ayconanw** [koolproxy/koolproxy_rules#9]
如题

**Comment by houzi-** [comment]
给链接，否则直接忽略

**Comment by ayconanw** [comment]
任意原图都会被屏蔽

Oct 27 21:20:52 sissylog: req should block=1 line=13909 url=http://rs.sinajs.cn/ht.gif?tids=4232443_1_1_a,4228584_1_2_a,4202802_1_3_a,4232313_1_4_d,4180133_1_5_c,4230128_1_6_c,2061438_1_7_c,4079806_1_8_c&uid=2729505461&bgid=1477574449836870&test=1&login=1&version=6&rnd=1477574454455
Oct 27 21:20:52 sissylog: req should block=1 line=13909 url=http://rs.sinajs.cn/xdht.gif?friendsdynamic=homepage&_rnd=147757445477899568&_uinfo=mozilla/5.0%20(windows%20nt%2010.0;%20win64;%20x64)%20applewebkit/537.36%20(khtml,%20like%20gecko)%20chrome/55.0.2883.21%20safari/537.36||
Oct 27 21:21:32 sissylog: resp should block=1 line=17767 url=http://ww2.sinaimg.cn/large/699132e6gw1f974m6xqhpj20go0b4gn4.jpg
