### ISSUE TITLE
IPAD 优酷订阅的个人中心打不开

### ISSUE THREAD

**Issue by iwsbiwy** [koolproxy/koolproxy_rules#90]
*os: ios
*platform(出现广告的平台):iPad
*version(系统版本): 10.3.1
*app(网站链接):优酷
*广告可以去除，但是订阅的个人中心打不开，提示加载失败，点击重试。

**Comment by houzi-** [comment]
没有问题

**Comment by iwsbiwy** [comment]
@houzi- 
app已经重新卸载安装过了。
![3](https://user-images.githubusercontent.com/40462471/42124628-f8cdab2a-7c98-11e8-9bb2-1886a25648b6.png)
![qq 20180630190710](https://user-images.githubusercontent.com/40462471/42124631-01b986be-7c99-11e8-9190-d737868fed71.png)
![qq 20180630190724](https://user-images.githubusercontent.com/40462471/42124630-0022e688-7c99-11e8-9ac3-bb7e7a4d5c12.png)

**Comment by houzi-** [comment]
安装证书

**Comment by iwsbiwy** [comment]
装过的，去网页广告 视频广告都没问题，就是这个订阅中心打不开，安卓没问题，手头没有IPhone，没法测试。
![qq 20180630191545](https://user-images.githubusercontent.com/40462471/42124678-045d229e-7c9a-11e8-87b4-d3b2e85aa651.jpg)

**Comment by houzi-** [comment]
你信任证书了没

**Comment by iwsbiwy** [comment]
没勾选，现在勾选了可以了，尴尬。多谢解答，给您添麻烦了。
