### ISSUE TITLE
使用koolproxy后NewPipe无法正常使用

### ISSUE THREAD

**Issue by rhjdvsgsgks** [koolproxy/koolproxy_rules#96]
使用koolproxy开启https过滤并且正确安装证书后[NewPipe](https://github.com/TeamNewPipe/NewPipe)无法正常使用，显示网络错误，关闭https过滤仅开启http过滤则可正常使用
os: Android
version: 8.1
app: [NewPipe](https://github.com/TeamNewPipe/NewPipe)
app version: [0.13.7](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.13.7)

**Comment by houzi-** [comment]
````@@@@|htttps://www.youtube.com````
使用这条规则加入到自定义，用这条规则意味着你放弃YouTube的过滤

**Comment by rhjdvsgsgks** [comment]
@houzi-  自己又试了一下，貌似改成
`@@@@||https://youtube.com`
才能正常使用，不知道为什么，很迷
